# Generated by Django 4.1.5 on 2023-01-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(max_length=5000)),
                (
                    "prediction",
                    models.CharField(
                        choices=[
                            ("INTJ", "INTJ"),
                            ("INTP", "INTP"),
                            ("ENTJ", "ENTJ"),
                            ("ENTP", "ENTP"),
                            ("INFJ", "INFJ"),
                            ("INFP", "INFP"),
                            ("ENFJ", "ENFJ"),
                            ("ENFP", "ENFP"),
                            ("ISTJ", "ISTJ"),
                            ("ESTJ", "ESTJ"),
                            ("ESFJ", "ESFJ"),
                            ("ISTP", "ISTP"),
                            ("ISFP", "ISFP"),
                            ("ESTP", "ESTP"),
                            ("ESFP", "ESFP"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
