# Generated by Django 4.1.5 on 2023-01-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.FileField(upload_to="")),
                ("preprocessed", models.BooleanField()),
            ],
        ),
    ]
