# Generated by Django 4.1.5 on 2023-02-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classification",
            "0003_trainmodel_accuracy_alter_trainmodel_dataset_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="classify",
            name="use_default",
            field=models.BooleanField(default=False),
        ),
    ]
